# ==============================================================================
# Composite Action: Setup Node.js + pnpm with Caching
# Reusable setup for all Node.js workflows
# ==============================================================================

name: Setup Node.js and pnpm
description: Setup Node.js, pnpm, and cache dependencies

inputs:
  node-version:
    description: Node.js version
    required: false
    default: '24'
  pnpm-version:
    description: pnpm version
    required: false
    default: '10.26.1'
  working-directory:
    description: Working directory for the project
    required: true

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

    - name: Cache pnpm dependencies
      uses: actions/cache@v5
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-${{ inputs.working-directory }}-${{ hashFiles(format('{0}/pnpm-lock.yaml', inputs.working-directory)) }}
        restore-keys: |
          ${{ runner.os }}-pnpm-${{ inputs.working-directory }}-

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: pnpm install --frozen-lockfile
